sudo: false
language: c++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - gfortran-4.8
    - libopenmpi-dev
    - libboost-all-dev
    - libfftw3-dev
install:
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"
    - export OMPI_MPICXX="g++-4.8"
    - export OMPI_MPICC="gcc-4.8"
    - export OMPI_MPIF90="gfortran-4.8"
    - export OMPI_MPIF77="gfortran-4.8"
    - which gfortran
    - which gfortran-4.8
compiler:
  - gcc
script:
  - make all
