language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - gfortran
    - libopenmpi-dev
    - libboost-all-dev
    - libfftw3-dev

matrix:
    exclude:
    - os: linux
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                                   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew cask uninstall oclint                                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gcc                                                                              ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install open-mpi                                                                         ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install fftw                                                                             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew upgrade cmake                                                                            ;fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then if [[ "$CC" == "gcc" ]]; then export CC=/usr/local/bin/gcc-8; export CXX=/usr/local/bin/g++-8 ;fi;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_Fortran_COMPILER=/usr/local/bin/gfortran-8                                       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_LINKER=clang++                                                                   ;fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Debug"

script:
  - cmake --build . --target install

