sudo: false
language: c++
addons:
  apt:
    packages:
    - gfortran
    - gcc
    - g++
    - libopenmpi-dev
    - libboost-all-dev
    - libfftw3-dev
install:
    - export CXX="/usr/bin/g++"
    - export CC="/usr/bin/gcc"
    - export FC="/usr/bin/gfortran"
    - export OMPI_MPICXX=$CXX
    - export OMPI_CXX=$CXX
    - export OMPI_MPICC=$CC
    - export OMPI_CC=$CC
    - export OMPI_MPIF90=$FC
    - export OMPI_FC=$FC
    - export OMPI_MPIF77=$FC
    - export OMPI_F77=$FC
compiler:
  - gcc
script:
  - make all
