language: cpp

matrix:
  include:

### since macOS homebrew's open-mpi is built against clang and the latest gfortran, the only working combinations are
### - for the cpp part:     Apple-clang (both the gcc and the clang front-ends) OR gcc@5 (ABI compatible with Apple-clang)
### - for the fortran part: ALWAYS gfortran-8
    - os: osx
      compiler: gcc
      name: macOS - gcc@5
      env:
        - MATRIX_EVAL="brew update && brew install gcc@5 gcc open-mpi fftw && brew upgrade cmake && CC=gcc-5 && CXX=g++-5 && FC=/usr/local/bin/gfortran-8"

    - os: osx
      compiler: gcc
      name: macOS - native gcc (llvm backend)
      env:
        - MATRIX_EVAL="brew update && brew install gcc open-mpi fftw && brew upgrade cmake && FC=/usr/local/bin/gfortran-8"

    - os: osx
      compiler: clang
      name: macOS - native clang
      env:
        - MATRIX_EVAL="brew update && brew install gcc open-mpi fftw && brew upgrade cmake && FC=/usr/local/bin/gfortran-8"

    - os: linux
      compiler: clang
      name: ubuntu - native clang
      addons:
        apt:
          update: true
          packages:
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="FC=/usr/bin/gfortran"

    - os: linux
      compiler: clang
      name: ubuntu - clang@3.6
      addons:
        apt:
          update: true
          packages:
            - clang-3.6
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6 && FC=/usr/bin/gfortran"

    - os: linux
      compiler: clang
      name: ubuntu - clang@3.8
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8 && FC=/usr/bin/gfortran"

    - os: linux
      compiler: clang
      name: ubuntu - clang@3.9
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9 && FC=/usr/bin/gfortran"

    - os: linux
      compiler: clang
      name: ubuntu - clang@4.0
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && FC=/usr/bin/gfortran"

    - os: linux
      compiler: clang
      name: ubuntu - clang@5.0
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && FC=/usr/bin/gfortran"

    - os: linux
      compiler: clang
      name: ubuntu - clang@6.0
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && FC=/usr/bin/gfortran"

    - os: linux
      compiler: gcc
      name: ubuntu - native gcc
      addons:
        apt:
          update: true
          packages:
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="FC=gfortran"

    - os: linux
      compiler: gcc
      name: ubuntu - gcc@4.9
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gfortran-4.9
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && FC=/usr/bin/gfortran-4.9"

    - os: linux
      compiler: gcc
      name: ubuntu - gcc@5.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gfortran-5
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && FC=/usr/bin/gfortran-5"

    - os: linux
      compiler: gcc
      name: ubuntu - gcc@6.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gfortran-6
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && FC=/usr/bin/gfortran-6"

    - os: linux
      compiler: gcc
      name: ubuntu - gcc@7.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran-7
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=/usr/bin/gfortran-7"

    - os: linux
      compiler: gcc
      name: ubuntu - gcc@8.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gfortran-8
            - gfortran
            - libopenmpi-dev
            - libboost-all-dev
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && FC=/usr/bin/gfortran-8"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_Fortran_COMPILER=$FC

script:
  - cmake --build . --target install
