language: cpp

os:
  - linux
  - osx

compiler: 
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:boost-latest/ppa'
    packages:
    - gfortran
    - gcc
    - g++
    - libopenmpi-dev
    - libboost-all-dev
    - libfftw3-dev
    - cmake

before_install:
  # OSX Setup 
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gcc                                                                          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew link gcc                                                                             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install open-mpi                                                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install fftw                                                                         ;fi

install:
  # OSX Setup
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_Fortran_COMPILER=/usr/local/bin/gfortran                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_C_COMPILER=/usr/local/bin/gcc                                                ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_CXX_COMPILER=/usr/local/bin/g++                                              ;fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_LINKER=clang++                                                               ;fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export FC=${CMAKE_Fortran_COMPILER}                                                       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CC=${CMAKE_C_COMPILER}                                                             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CXX=${CMAKE_CXX_COMPILER}                                                          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_MPICXX=$CXX                                                                   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_CXX=$CXX                                                                      ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_MPICC=$CC                                                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_CC=$CC                                                                        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_MPIF90=$FC                                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_FC=$FC                                                                        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_MPIF77=$FC                                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export OMPI_F77=$FC                                                                       ;fi

  # Linux Setup 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="/usr/bin/g++"                                                                 ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC="/usr/bin/gcc"                                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export FC="/usr/bin/gfortran"                                                             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_MPICXX=$CXX                                                                   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_CXX=$CXX                                                                      ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_MPICC=$CC                                                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_CC=$CC                                                                        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_MPIF90=$FC                                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_FC=$FC                                                                        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_MPIF77=$FC                                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OMPI_F77=$FC                                                                       ;fi

script:
  - mkdir build && cd build && cmake .. && cmake --build . --target install

