sudo: false
language: c++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - gfortran-4.9
    - libopenmpi-dev
    - libboost-all-dev
    - libfftw3-dev
install:
    - export CXX="/usr/bin/g++-4.9"
    - export CC="/usr/bin/gcc-4.9"
    - export FC="/usr/bin/gfortran-4.9"
    - export OMPI_MPICXX=$CXX
    - export OMPI_MPICC=$CC
    - export OMPI_MPIF90=$FC
    - export OMPI_MPIF77=$FC
    - $CXX --version
    - $FC --version
    - $OMPI_MPIF90 --version
compiler:
  - gcc
script:
  - make all
