name: FORD Documentation
uses: ResearchSoftwareActions/ford-build@v1.0
on: push
author: The ALaDyn Collaboration
description: Build FORD documentation of the ALaDyn code
inputs:
  project_file:
    description: Name of the FORD project file
    required: true
    default: aladyn_doc.md
outputs:
  output_dir:
    description: Path to the directory where documentation is written
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project_file }}
branding:
  icon: book
  color: orange