env_lpf2_evolve – ALaDyn
env_lpf2_evolve Subroutine
99 statements
Source File
public subroutine env_lpf2_evolve(it_loc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it_loc
Calls
Called by
Contents
None
Call graph
env_lpf2_evolve calls flux, fluid_curr_accumulate, loc_npart, spec, ion_min, env_amp_prepare, set_env_density, ebfp, jc, update_adam_bash_fluid_variables, env_fields_average, curr_mpi_collect, set_env_momentum_density_flux, atomic_number, env_den_collect, advance_lpf_fields, env_amp_two_fields_prepare, init_random_seed, advance_lpf_envelope, env_two_fields_average, enable_ionization
fluid_curr_accumulate calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd
env_amp_prepare calls env_grad
update_adam_bash_fluid_variables calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd, lorentz_fact, nc_fluid_density_momenta
env_fields_average calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
env_den_collect calls fill_curr_yzxbdsdata, loc_yg, den_zyxbd, loc_zg
advance_lpf_fields calls ef_bds, field_xadvect, fill_ebfield_yzxbdsdata, rotb, rote, bf_bds
env_amp_two_fields_prepare calls env_grad
advance_lpf_envelope calls env_maxw_solve, env_bds, fill_ebfield_yzxbdsdata, env_lpf_solve
env_maxw_solve calls potential_lapl
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
field_xadvect calls trid_der1
env_bds calls loc_yg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
fill_curr_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
env_lpf_solve calls pp_lapl
rote calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
nc_fluid_density_momenta calls loc_yg, loc_zg
pp_lapl calls loc_yg, loc_zg
env_run calls env_lpf2_evolve
env_cycle calls env_run
aladyn calls env_cycle