env_run – ALaDyn
env_run Subroutine
23 statements
Source File
public subroutine env_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
env_run calls env_lpf2_evolve, comoving_coordinate, lp_window_xshift
env_lpf2_evolve calls flux, fluid_curr_accumulate, loc_npart, spec, ion_min, env_amp_prepare, set_env_density, ebfp, jc, update_adam_bash_fluid_variables, env_fields_average, curr_mpi_collect, set_env_momentum_density_flux, atomic_number, env_den_collect, advance_lpf_fields, env_amp_two_fields_prepare, init_random_seed, advance_lpf_envelope, env_two_fields_average, enable_ionization
comoving_coordinate calls cell_part_dist, particles_inject
lp_window_xshift calls fields_left_xshift, cell_part_dist, part_numbers, particles_inject, fluid_left_xshift
fields_left_xshift calls exchange_bdx_data
fluid_curr_accumulate calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd
env_amp_prepare calls env_grad
update_adam_bash_fluid_variables calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd, lorentz_fact, nc_fluid_density_momenta
env_fields_average calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
env_den_collect calls fill_curr_yzxbdsdata, loc_yg, den_zyxbd, loc_zg
advance_lpf_fields calls ef_bds, field_xadvect, fill_ebfield_yzxbdsdata, rotb, rote, bf_bds
cell_part_dist calls loc_npart, spec, ebfp, v_realloc
part_numbers calls loc_npart, intvec_distribute
env_amp_two_fields_prepare calls env_grad
particles_inject calls loc_npart, add_particles, v_realloc
fluid_left_xshift calls exchange_bdx_data
advance_lpf_envelope calls env_maxw_solve, env_bds, fill_ebfield_yzxbdsdata, env_lpf_solve
env_maxw_solve calls potential_lapl
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
field_xadvect calls trid_der1
add_particles calls init_random_seed, gasdev
env_bds calls loc_yg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
fill_curr_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
env_lpf_solve calls pp_lapl
rote calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
nc_fluid_density_momenta calls loc_yg, loc_zg
intvec_distribute calls mpi_recv, mpi_bcast, mpi_send
pp_lapl calls loc_yg, loc_zg
env_cycle calls env_run
aladyn calls env_cycle