Env_cycle – ALaDyn
Env_cycle Subroutine
23 statements
Source File
subroutine Env_cycle()
Arguments
None
Calls
Called by
Contents
None
Call graph
env_cycle calls timing, error_message, data_out, env_run, beam_inject, part_numbers
timing calls part_numbers, max_pmemory_check, tot_num_part
data_out calls envar, env_fields_out, fields_out_new, den_energy_out, fields_out, create_timestep_folder, env_two_fields_out, fluid_den_mom_out, part_pdata_out, prl_den_energy_interp
env_run calls env_lpf2_evolve, comoving_coordinate, lp_window_xshift
beam_inject calls pot, initial_beam_fields, spec, beam_data, loc_npart, ebfb, mpi_beam_ftgrid_distribute, ebf_bunch, fill_ebfield_yzxbdsdata, ebf, lp_end, ebfp, jc, mpi_beam_distribute, bunch, init_random_seed, p_alloc, loc_nbpart
part_numbers calls loc_npart, intvec_distribute
initial_beam_fields calls loc_yg, loc_zg
envar calls loc_npart, envelope_struct_data, allreduce_dpreal, enb_bunch, mass
beam_data calls ebfb, exchange_2d_grdata, unit_charge
env_fields_out calls exchange_pdata
fields_out_new calls endian, mpi_write_field
mpi_beam_ftgrid_distribute calls ebfb, bunch, loc_nbpart
max_pmemory_check calls allreduce_dpreal
fill_ebfield_yzxbdsdata calls exchange_bdx_data
den_energy_out calls exchange_pdata, endian
fields_out calls exchange_pdata, endian
env_lpf2_evolve calls spec, loc_npart, ebfp, jc, init_random_seed, flux, fluid_curr_accumulate, ion_min, env_amp_prepare, set_env_density, update_adam_bash_fluid_variables, env_fields_average, curr_mpi_collect, set_env_momentum_density_flux, atomic_number, env_den_collect, advance_lpf_fields, env_amp_two_fields_prepare, advance_lpf_envelope, env_two_fields_average, enable_ionization
env_two_fields_out calls exchange_pdata
comoving_coordinate calls cell_part_dist, particles_inject
mpi_beam_distribute calls ebfb, bunch, loc_nbpart
fluid_den_mom_out calls exchange_pdata, endian
tot_num_part calls loc_npart
part_pdata_out calls loc_npart, intvec_distribute, mpi_write_part, endian
lp_window_xshift calls part_numbers, fields_left_xshift, cell_part_dist, particles_inject, fluid_left_xshift
prl_den_energy_interp calls spec, loc_npart, jc, env, loc_yg, loc_zg, den_zyxbd, mass
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
fields_left_xshift calls exchange_bdx_data
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
env_amp_prepare calls env_grad
envelope_struct_data calls allreduce_dpreal
allreduce_dpreal calls mpi_allreduce
mpi_write_part calls mpi_file_open, mpi_file_set_view, mpi_file_write, mpi_file_close
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd, lorentz_fact, nc_fluid_density_momenta
env_fields_average calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
env_den_collect calls loc_yg, loc_zg, fill_curr_yzxbdsdata, den_zyxbd
advance_lpf_fields calls fill_ebfield_yzxbdsdata, ef_bds, field_xadvect, rotb, rote, bf_bds
cell_part_dist calls spec, loc_npart, ebfp, v_realloc
env_amp_two_fields_prepare calls env_grad
particles_inject calls loc_npart, add_particles, v_realloc
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
fluid_left_xshift calls exchange_bdx_data
mpi_write_field calls mpi_file_open, mpi_file_set_view, mpi_file_write, mpi_file_close
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
bunch_corr calls allreduce_dpreal
env_maxw_solve calls potential_lapl
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
field_xadvect calls trid_der1
add_particles calls init_random_seed, gasdev
env_bds calls loc_yg, loc_zg
fill_curr_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
env_lpf_solve calls pp_lapl
rote calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
nc_fluid_density_momenta calls loc_yg, loc_zg
pp_lapl calls loc_yg, loc_zg
aladyn calls env_cycle