fft_2d_psolv – ALaDyn
fft_2d_psolv Subroutine
54 statements
Source File
public subroutine fft_2d_psolv(rho, pot1, omp0, n1, n1_loc, n2, n2_loc, n3, n3_loc, i1, i2, j1, j2, k1, k2, ft_mod, sym, sind)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: rho(:,:,:,:)
real(kind=dp), intent(inout) :: pot1(:,:,:,:)
real(kind=dp), intent(in) :: omp0
integer, intent(in) :: n1
integer, intent(in) :: n1_loc
integer, intent(in) :: n2
integer, intent(in) :: n2_loc
integer, intent(in) :: n3
integer, intent(in) :: n3_loc
integer, intent(in) :: i1
integer, intent(in) :: i2
integer, intent(in) :: j1
integer, intent(in) :: j2
integer, intent(in) :: k1
integer, intent(in) :: k2
integer, intent(in) :: ft_mod
integer, intent(in) :: sym
integer, intent(in) :: sind
Calls
Called by
Contents
None
Call graph
fft_2d_psolv calls pftw2d_sc, ftw_init, mpi_yzft_ord, mpi_ftw_alloc, pftw2d, ftw_end, ft_overset_grid, mpi_ftw_dalloc, unif_to_str_field_interp, beam_2d_potential, all_gather_dpreal
pftw2d_sc calls swap_xz_3data_inv, swap_xy_3data, ftw1d_sc, swap_xz_3data, swap_xy_3data_inv
pftw2d calls swap_xz_3data_inv, swap_xy_3data, swap_xz_3data, ftw1d, swap_xy_3data_inv
ft_overset_grid calls yp_prev, zp_next, comm_col, yp_next, zp_prev
unif_to_str_field_interp calls yft_ind, loc_zft, loc_yg, zft_ind, loc_zg, loc_yft
swap_xz_3data_inv calls zp_next, comm_col, zp_prev
swap_xy_3data calls yp_prev, comm_col, yp_next
ftw1d_sc calls determine_kind, fftw_execute_r2r, logical_dimension
swap_xz_3data calls zp_next, comm_col, zp_prev
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
swap_xy_3data_inv calls yp_prev, comm_col, yp_next
set_wake_potential calls fft_2d_psolv