init – ALaDyn
init Subroutine
14 statements
Source File
public subroutine init()
Arguments
None
Calls
Called by
Contents
None
Call graph
init calls set_envelope, cp_pulse, part_distribute, lp_pulse
set_envelope calls xf_loc, xc_loc, init_envelope_field, y0_cent, init_gprof_envelope_field, lp_end, lpx, lp_delay, lp_in, loc_xgrid, z0_cent
cp_pulse calls lp_end, lpx, lp_in, init_cp_fields, loc_xgrid
part_distribute calls multi_layer_twosp_target, preplasma_multisp, one_layer_nano_tubes, multi_layer_gas_target, multi_layer_threesp_target, one_layer_nano_wires
lp_pulse calls init_lp_inc0_fields, xf_loc, xc_loc, y0_cent, lp_end, lpx, lp_delay, lp_in, loc_xgrid, z0_cent
init_lp_inc0_fields calls loc_ygrid, get_2dlaser_gprof_fields_lp, loc_zgrid, loc_yg, get_laser_gprof_fields_lp, loc_zg, loc_xg, get_plane_wave_lp, get_laser_fields_lp, get_2dlaser_fields_lp
multi_layer_twosp_target calls spec, wghpt, set_uniform_yz_distrib, loc_xpt, xpt, loc_wghx, p_alloc
preplasma_multisp calls spec, wghpt, set_uniform_yz_distrib, loc_xpt, xpt, loc_wghx, p_alloc
init_envelope_field calls loc_ygrid, loc_zgrid, loc_yg, loc_zg, loc_xg
one_layer_nano_tubes calls loc_ypt, spec, loc_zpt, wghpt, ypt, gasdev, loc_xpt, mpi_yz_part_distrib, loc_wghyz, zpt, xpt, init_random_seed, p_alloc
init_gprof_envelope_field calls loc_ygrid, loc_zgrid, loc_yg, loc_zg, loc_xg
multi_layer_gas_target calls spec, mpi_x_part_distrib, wghpt, set_uniform_yz_distrib, loc_xpt, xpt, loc_wghx, p_alloc
multi_layer_threesp_target calls spec, wghpt, set_uniform_yz_distrib, loc_xpt, xpt, loc_wghx, p_alloc
init_cp_fields calls loc_ygrid, get_laser_fields_cp, loc_zgrid, get_plane_wave_cp, loc_yg, loc_zg, loc_xg
one_layer_nano_wires calls loc_ypt, spec, loc_zpt, wghpt, ypt, set_pgrid_ind, loc_xpt, mpi_yz_part_distrib, loc_wghyz, zpt, xpt, loc_wghx, p_alloc
mpi_x_part_distrib calls wghpt, loc_xpt, xpt, loc_wghx
set_pgrid_ind calls ypt, zpt
set_uniform_yz_distrib calls loc_ypt, loc_zpt, ypt, set_pgrid_ind, mpi_yz_part_distrib, loc_wghyz, zpt
mpi_yz_part_distrib calls loc_ypt, loc_zpt, ypt, loc_wghyz, zpt
start calls init
aladyn calls start