intvec_distribute – ALaDyn
intvec_distribute Subroutine
15 statements
Source File
public subroutine intvec_distribute(ns, nc, nproc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ns
integer, intent(inout) :: nc(:)
integer, intent(in) :: nproc
Calls
Called by
Contents
None
Call graph
intvec_distribute calls mpi_bcast, mpi_send, mpi_recv
part_high_gamma_out calls intvec_distribute
part_pdata_out calls intvec_distribute
dump_data calls intvec_distribute
restart calls intvec_distribute
part_bdata_out calls intvec_distribute
part_ionz_out calls intvec_distribute
part_numbers calls intvec_distribute
lp_window_xshift calls part_numbers
timing calls part_numbers
aladyn calls part_numbers, start, env_cycle, lp_cycle
data_out calls part_pdata_out
start calls restart
env_cycle calls part_numbers, timing, data_out, env_run
lp_cycle calls timing, data_out, lp_run
lp_run calls lp_window_xshift
env_run calls lp_window_xshift