Lp_cycle – ALaDyn
Lp_cycle Subroutine
15 statements
Source File
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
Calls
Called by
Contents
None
Call graph
lp_cycle calls error_message, data_out, lp_run, timing
data_out calls create_timestep_folder, part_pdata_out, prl_den_energy_interp, env_two_fields_out, envar, env_fields_out, fields_out_new, den_energy_out, fields_out, fluid_den_mom_out
lp_run calls lpf2_evolve, lp_window_xshift, comoving_coordinate
timing calls max_pmemory_check, tot_num_part, part_numbers
max_pmemory_check calls allreduce_dpreal
lpf2_evolve calls pfields_prepare, fluid_curr_accumulate, loc_npart, spec, ion_min, set_momentum_density_flux, init_random_seed, ebfp, jc, update_adam_bash_fluid_variables, atomic_number, advance_lpf_fields
lp_window_xshift calls part_numbers, fields_left_xshift, cell_part_dist, particles_inject, fluid_left_xshift
part_pdata_out calls loc_npart, mpi_write_part, endian, intvec_distribute
tot_num_part calls loc_npart
prl_den_energy_interp calls loc_npart, spec, env, jc, loc_yg, loc_zg, den_zyxbd, mass
env_two_fields_out calls exchange_pdata
envar calls loc_npart, envelope_struct_data, allreduce_dpreal, enb_bunch, mass
env_fields_out calls exchange_pdata
comoving_coordinate calls cell_part_dist, particles_inject
part_numbers calls loc_npart, intvec_distribute
fields_out_new calls endian, mpi_write_field
den_energy_out calls exchange_pdata, endian
fields_out calls exchange_pdata, endian
fluid_den_mom_out calls exchange_pdata, endian
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
fields_left_xshift calls exchange_bdx_data
fluid_curr_accumulate calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd
envelope_struct_data calls allreduce_dpreal
allreduce_dpreal calls mpi_allreduce
update_adam_bash_fluid_variables calls unit_charge, fill_ebfield_yzxbdsdata, field_xyzbd, lorentz_fact, nc_fluid_density_momenta
mpi_write_part calls mpi_file_open, mpi_file_set_view, mpi_file_write, mpi_file_close
advance_lpf_fields calls ef_bds, field_xadvect, fill_ebfield_yzxbdsdata, rotb, rote, bf_bds
cell_part_dist calls loc_npart, spec, ebfp, v_realloc
particles_inject calls loc_npart, add_particles, v_realloc
fluid_left_xshift calls exchange_bdx_data
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
mpi_write_field calls mpi_file_open, mpi_file_set_view, mpi_file_write, mpi_file_close
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
bunch_corr calls allreduce_dpreal
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
field_xadvect calls trid_der1
add_particles calls gasdev, init_random_seed
fill_ebfield_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
rote calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
nc_fluid_density_momenta calls loc_yg, loc_zg
aladyn calls lp_cycle