lp_pulse – ALaDyn
lp_pulse Subroutine
54 statements
Source File
public subroutine lp_pulse(lp_mod, part_in)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lp_mod
real(kind=dp), intent(out) :: part_in
Calls
Called by
Contents
None
Call graph
lp_pulse calls y0_cent, lp_delay, init_lp_inc0_fields, lp_in, xf_loc, lp_end, z0_cent, lpx, xc_loc, loc_xgrid
init_lp_inc0_fields calls loc_yg, loc_ygrid, get_laser_gprof_fields_lp, get_plane_wave_lp, get_2dlaser_gprof_fields_lp, loc_zgrid, get_laser_fields_lp, loc_zg, loc_xg, get_2dlaser_fields_lp
init calls lp_pulse
start calls init
aladyn calls start