lp_run – ALaDyn
lp_run Subroutine
21 statements
Source File
public subroutine lp_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
lp_run calls lp_window_xshift, comoving_coordinate, lpf2_evolve
lp_window_xshift calls fluid_left_xshift, fields_left_xshift, cell_part_dist, part_numbers, particles_inject
comoving_coordinate calls cell_part_dist, particles_inject
lpf2_evolve calls pfields_prepare, set_momentum_density_flux, update_adam_bash_fluid_variables, init_random_seed, ebfp, fluid_curr_accumulate, loc_npart, spec, ion_min, atomic_number, advance_lpf_fields, jc
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
fluid_left_xshift calls exchange_bdx_data
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, field_xyzbd, unit_charge, nc_fluid_density_momenta, lorentz_fact
fields_left_xshift calls exchange_bdx_data
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, field_xyzbd, unit_charge
cell_part_dist calls ebfp, loc_npart, spec, v_realloc
advance_lpf_fields calls field_xadvect, fill_ebfield_yzxbdsdata, rotb, rote, bf_bds, ef_bds
part_numbers calls loc_npart, intvec_distribute
particles_inject calls loc_npart, add_particles, v_realloc
field_xadvect calls trid_der1
add_particles calls gasdev, init_random_seed
fill_ebfield_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
nc_fluid_density_momenta calls loc_yg, loc_zg
rote calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
intvec_distribute calls mpi_recv, mpi_bcast, mpi_send
ef_bds calls loc_yg, loc_zgrid, loc_zg, loc_xg
lp_cycle calls lp_run
aladyn calls lp_cycle