lp_window_xshift – ALaDyn
lp_window_xshift Subroutine
62 statements
Source File
public subroutine lp_window_xshift(witr, init_iter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: witr
integer, intent(in) :: init_iter
Calls
Called by
Contents
None
Call graph
lp_window_xshift calls fluid_left_xshift, fields_left_xshift, cell_part_dist, part_numbers, particles_inject
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
cell_part_dist calls v_realloc, loc_npart, spec, ebfp
part_numbers calls loc_npart, intvec_distribute
particles_inject calls add_particles, loc_npart, v_realloc
add_particles calls gasdev, init_random_seed
intvec_distribute calls mpi_recv, mpi_bcast, mpi_send
lp_run calls lp_window_xshift
env_run calls lp_window_xshift
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle