multi_layer_gas_target – ALaDyn
multi_layer_gas_target Subroutine
424 statements
Source File
private subroutine multi_layer_gas_target(layer_mod, nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: layer_mod
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
multi_layer_gas_target calls wghpt, xpt, loc_wghx, loc_xpt, p_alloc, spec, mpi_x_part_distrib, set_uniform_yz_distrib
mpi_x_part_distrib calls wghpt, xpt, loc_wghx, loc_xpt
set_uniform_yz_distrib calls ypt, zpt, set_pgrid_ind, loc_ypt, loc_zpt, mpi_yz_part_distrib, loc_wghyz
set_pgrid_ind calls ypt, zpt
mpi_yz_part_distrib calls ypt, zpt, loc_ypt, loc_zpt, loc_wghyz
part_distribute calls multi_layer_gas_target
init calls part_distribute
start calls init
aladyn calls start