one_layer_nano_wires – ALaDyn
one_layer_nano_wires Subroutine
375 statements
Source File
private subroutine one_layer_nano_wires(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
one_layer_nano_wires calls ypt, zpt, xpt, loc_wghx, set_pgrid_ind, loc_xpt, loc_ypt, p_alloc, spec, loc_zpt, mpi_yz_part_distrib, loc_wghyz, wghpt
set_pgrid_ind calls ypt, zpt
mpi_yz_part_distrib calls ypt, zpt, loc_ypt, loc_zpt, loc_wghyz
part_distribute calls one_layer_nano_wires
init calls part_distribute
start calls init
aladyn calls start