part_distribute – ALaDyn
part_distribute Subroutine
38 statements
Source File
public subroutine part_distribute(id, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
part_distribute calls one_layer_nano_tubes, multi_layer_twosp_target, multi_layer_threesp_target, multi_layer_gas_target, preplasma_multisp, one_layer_nano_wires
one_layer_nano_tubes calls gasdev, ypt, zpt, xpt, init_random_seed, loc_xpt, loc_ypt, p_alloc, spec, loc_zpt, mpi_yz_part_distrib, loc_wghyz, wghpt
multi_layer_twosp_target calls xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt, p_alloc, spec, wghpt
multi_layer_threesp_target calls xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt, p_alloc, spec, wghpt
multi_layer_gas_target calls xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt, p_alloc, spec, mpi_x_part_distrib, wghpt
preplasma_multisp calls xpt, loc_wghx, set_uniform_yz_distrib, loc_xpt, p_alloc, spec, wghpt
one_layer_nano_wires calls ypt, zpt, xpt, loc_wghx, loc_xpt, set_pgrid_ind, loc_ypt, p_alloc, spec, loc_zpt, mpi_yz_part_distrib, loc_wghyz, wghpt
set_uniform_yz_distrib calls ypt, zpt, set_pgrid_ind, loc_ypt, loc_zpt, mpi_yz_part_distrib, loc_wghyz
set_pgrid_ind calls ypt, zpt
mpi_x_part_distrib calls xpt, loc_wghx, loc_xpt, wghpt
mpi_yz_part_distrib calls ypt, zpt, loc_ypt, loc_zpt, loc_wghyz
init calls part_distribute
start calls init
aladyn calls start