restart – ALaDyn
restart Subroutine
369 statements
Source File
public subroutine restart(it_loc, tloc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: it_loc
real(kind=dp), intent(out) :: tloc
Calls
Called by
Contents
None
Call graph
restart calls loc_ypt, loc_npart, up, loc_zpt, spec, wghpt, fluid_x_profile, ebf, env, real_bcast, env1, up0, vint_2d_bcast, exchange_2d_grdata, loc_wghyz, fluid_yz_profile, exchange_1d_grdata, xpt, p_alloc, vint_bcast, intvec_distribute
real_bcast calls mpi_bcast
vint_bcast calls mpi_bcast
intvec_distribute calls mpi_bcast, mpi_send, mpi_recv
start calls restart
aladyn calls start