set_wake_potential – ALaDyn
set_wake_potential Subroutine
21 statements
Source File
public subroutine set_wake_potential()
Arguments
None
Calls
Contents
None
Call graph
set_wake_potential calls fill_curr_yzxbdsdata, loc_npart, spec, fill_density_data, fft_2d_psolv, jc
fill_curr_yzxbdsdata calls exchange_bdx_data
fill_density_data calls loc_ygrid, loc_zgrid, x, y, z
fft_2d_psolv calls pftw2d_sc, ftw_init, mpi_yzft_ord, mpi_ftw_alloc, pftw2d, ftw_end, all_gather_dpreal, ft_overset_grid, mpi_ftw_dalloc, unif_to_str_field_interp, beam_2d_potential
pftw2d_sc calls swap_xz_3data_inv, swap_xy_3data, ftw1d_sc, swap_xz_3data, swap_xy_3data_inv
pftw2d calls swap_xz_3data_inv, swap_xy_3data, swap_xz_3data, ftw1d, swap_xy_3data_inv
ft_overset_grid calls yp_prev, zp_next, comm_col, yp_next, zp_prev
unif_to_str_field_interp calls yft_ind, loc_zft, loc_yg, zft_ind, loc_zg, loc_yft
swap_xz_3data_inv calls zp_next, comm_col, zp_prev
swap_xy_3data calls yp_prev, comm_col, yp_next
ftw1d_sc calls determine_kind, fftw_execute_r2r, logical_dimension
swap_xz_3data calls zp_next, comm_col, zp_prev
ftw1d calls fftw_execute_dft_r2c, fftw_execute_dft_c2r
swap_xy_3data_inv calls yp_prev, comm_col, yp_next