set_grid_charge – ALaDyn
set_grid_charge Subroutine
87 statements
Source File
public subroutine set_grid_charge(sp_loc, pt, den, np, ic)
Arguments
Type Intent Optional Attributes Name
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: pt(:,:)
real(kind=dp), intent(inout) :: den(:,:,:,:)
integer, intent(in) :: np
integer, intent(in) :: ic
Calls
Contents
None
Call graph
set_grid_charge calls qden_3d_wgh, qden_2d_wgh, set_local_3d_positions, set_local_2d_positions, qden_1d_wgh
set_local_3d_positions calls map3d_part_sind
set_local_2d_positions calls map2dy_part_sind
map2dy_part_sind calls invert_uniform_grid, invert_stretched_grid
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dz_part_sind calls invert_uniform_grid, invert_stretched_grid