Start – ALaDyn
Start Subroutine
193 statements
Source File
public subroutine Start()
Start subroutine. It reads the input file, initializes the variables and allocates the needed arrays before to start the simulation.
Arguments
None
Calls
Called by
Contents
None
Call graph
start calls create_initial_folders, loc_ygrid, init, fluid_alloc, set_loc_grid_param, restart, ion_min, mpi_barrier, loc_yft, set_output_grid, set_initial_param, mpi_buffer_alloc, v_alloc, start_parallel, end_parallel, yft_ind, set_fyzxgrid, loc_yg, mpi_loc_grid, set_ftgrid, atomic_number, write_read_nml, float, read_main_input, loc_yftgrid, set_fxgrid, set_field_param
init calls cp_pulse, lp_pulse, part_distribute, set_envelope
restart calls loc_ypt, loc_npart, up, loc_zpt, spec, wghpt, fluid_x_profile, ebf, env, real_bcast, env1, up0, vint_2d_bcast, exchange_2d_grdata, loc_wghyz, fluid_yz_profile, exchange_1d_grdata, xpt, p_alloc, vint_bcast, intvec_distribute
set_initial_param calls z, set_grid, y
set_ftgrid calls select_str_to_ft_grid, set_ftyzgrid
read_main_input calls read_input_nml
cp_pulse calls lp_end, lpx, lp_in, init_cp_fields, loc_xgrid
real_bcast calls mpi_bcast
lp_pulse calls init_lp_inc0_fields, xf_loc, xc_loc, y0_cent, lp_end, lpx, lp_delay, lp_in, loc_xgrid, z0_cent
part_distribute calls multi_layer_twosp_target, preplasma_multisp, one_layer_nano_tubes, multi_layer_gas_target, multi_layer_threesp_target, one_layer_nano_wires
read_input_nml calls consistency_check_number_of_particles_comp, consistency_check_grid
set_envelope calls xf_loc, xc_loc, init_envelope_field, y0_cent, init_gprof_envelope_field, lp_end, lpx, lp_delay, lp_in, loc_xgrid, z0_cent
vint_bcast calls mpi_bcast
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
init_lp_inc0_fields calls loc_ygrid, loc_yg, get_2dlaser_gprof_fields_lp, loc_zgrid, get_laser_gprof_fields_lp, loc_zg, loc_xg, get_plane_wave_lp, get_laser_fields_lp, get_2dlaser_fields_lp
multi_layer_twosp_target calls spec, wghpt, xpt, p_alloc, set_uniform_yz_distrib, loc_xpt, loc_wghx
preplasma_multisp calls spec, wghpt, xpt, p_alloc, set_uniform_yz_distrib, loc_xpt, loc_wghx
init_envelope_field calls loc_ygrid, loc_yg, loc_zgrid, loc_zg, loc_xg
one_layer_nano_tubes calls loc_ypt, loc_zpt, spec, wghpt, loc_wghyz, xpt, p_alloc, ypt, gasdev, loc_xpt, mpi_yz_part_distrib, zpt, init_random_seed
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
init_gprof_envelope_field calls loc_ygrid, loc_yg, loc_zgrid, loc_zg, loc_xg
multi_layer_gas_target calls spec, wghpt, xpt, p_alloc, mpi_x_part_distrib, set_uniform_yz_distrib, loc_xpt, loc_wghx
multi_layer_threesp_target calls spec, wghpt, xpt, p_alloc, set_uniform_yz_distrib, loc_xpt, loc_wghx
init_cp_fields calls loc_ygrid, loc_yg, get_laser_fields_cp, loc_zgrid, get_plane_wave_cp, loc_zg, loc_xg
one_layer_nano_wires calls loc_ypt, loc_zpt, spec, wghpt, loc_wghyz, xpt, p_alloc, ypt, set_pgrid_ind, loc_xpt, mpi_yz_part_distrib, zpt, loc_wghx
from_ppc_to_npx_npy_npz calls isprime
mpi_x_part_distrib calls wghpt, xpt, loc_xpt, loc_wghx
set_pgrid_ind calls ypt, zpt
set_uniform_yz_distrib calls loc_ypt, loc_zpt, loc_wghyz, ypt, set_pgrid_ind, mpi_yz_part_distrib, zpt
mpi_yz_part_distrib calls loc_ypt, loc_zpt, loc_wghyz, ypt, zpt
aladyn calls start