t_particles_collect – ALaDyn
t_particles_collect Subroutine
67 statements
Source File
public subroutine t_particles_collect(time_ind)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: time_ind
Calls
Contents
None
Call graph
t_particles_collect calls loc_ygrid, pdata_tracking, str_indx, loc_zgrid, track_aux, loc_npart, spec, loc_tpart, intvec_distribute, loc_xgrid, exchange_1d_grdata