aladyn – ALaDyn
aladyn Program
168 statements
Source File
Uses
start_all
diag_part_and_fields
run_data_info
pic_out_util
pic_out
init_beam_part_distrib
pic_evolve
env_evolve
Calls
Contents
Subroutines
Lp_cycle Env_cycle data_out
Subroutines
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
subroutine Env_cycle()
Arguments
None
subroutine data_out()
Arguments
None
Call graph
aladyn calls initial_run_info, max_pmemory_check, lp_cycle, end_parallel, final_run_info, mpi_barrier, part_numbers, start, env_cycle
max_pmemory_check calls allreduce_dpreal
lp_cycle calls lp_run, timing, error_message, data_out
part_numbers calls loc_npart, intvec_distribute
start calls end_parallel, mpi_barrier, create_initial_folders, loc_ygrid, init, fluid_alloc, set_loc_grid_param, restart, ion_min, loc_yft, set_output_grid, set_initial_param, mpi_buffer_alloc, v_alloc, start_parallel, yft_ind, set_fyzxgrid, loc_yg, mpi_loc_grid, set_ftgrid, atomic_number, write_read_nml, float, read_main_input, loc_yftgrid, set_fxgrid, set_field_param
env_cycle calls part_numbers, env_run, timing, error_message, data_out, beam_inject
init calls cp_pulse, lp_pulse, part_distribute, set_envelope
lp_run calls lpf2_evolve, comoving_coordinate, lp_window_xshift
restart calls loc_npart, intvec_distribute, loc_ypt, up, spec, loc_zpt, wghpt, fluid_x_profile, ebf, env, real_bcast, env1, up0, vint_2d_bcast, exchange_2d_grdata, loc_wghyz, fluid_yz_profile, exchange_1d_grdata, xpt, p_alloc, vint_bcast
env_run calls env_lpf2_evolve, comoving_coordinate, lp_window_xshift
set_initial_param calls z, set_grid, y
timing calls max_pmemory_check, part_numbers, tot_num_part
allreduce_dpreal calls mpi_allreduce
data_out calls envar, env_fields_out, fields_out_new, den_energy_out, fields_out, create_timestep_folder, env_two_fields_out, fluid_den_mom_out, part_pdata_out, prl_den_energy_interp
beam_inject calls loc_npart, pot, initial_beam_fields, spec, beam_data, ebfb, mpi_beam_ftgrid_distribute, ebf_bunch, fill_ebfield_yzxbdsdata, ebf, lp_end, ebfp, jc, mpi_beam_distribute, bunch, init_random_seed, p_alloc, loc_nbpart
set_ftgrid calls select_str_to_ft_grid, set_ftyzgrid
read_main_input calls read_input_nml
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
initial_beam_fields calls loc_yg, loc_zg
envar calls loc_npart, allreduce_dpreal, envelope_struct_data, enb_bunch, mass
env_fields_out calls exchange_pdata
beam_data calls ebfb, exchange_2d_grdata, unit_charge
fields_out_new calls endian, mpi_write_field
mpi_beam_ftgrid_distribute calls ebfb, bunch, loc_nbpart
lpf2_evolve calls loc_npart, ion_min, atomic_number, spec, ebfp, jc, pfields_prepare, fluid_curr_accumulate, set_momentum_density_flux, init_random_seed, update_adam_bash_fluid_variables, advance_lpf_fields
fill_ebfield_yzxbdsdata calls exchange_bdx_data
cp_pulse calls lp_end, lpx, lp_in, init_cp_fields, loc_xgrid
den_energy_out calls exchange_pdata, endian
real_bcast calls mpi_bcast
fields_out calls exchange_pdata, endian
env_lpf2_evolve calls loc_npart, ion_min, atomic_number, spec, ebfp, jc, init_random_seed, flux, fluid_curr_accumulate, env_amp_prepare, set_env_density, update_adam_bash_fluid_variables, env_fields_average, curr_mpi_collect, set_env_momentum_density_flux, advance_lpf_fields, env_den_collect, env_amp_two_fields_prepare, advance_lpf_envelope, env_two_fields_average, enable_ionization
lp_pulse calls lp_end, init_lp_inc0_fields, xf_loc, xc_loc, y0_cent, lpx, lp_delay, lp_in, loc_xgrid, z0_cent
part_distribute calls multi_layer_twosp_target, preplasma_multisp, one_layer_nano_tubes, multi_layer_gas_target, multi_layer_threesp_target, one_layer_nano_wires
env_two_fields_out calls exchange_pdata
comoving_coordinate calls cell_part_dist, particles_inject
read_input_nml calls consistency_check_number_of_particles_comp, consistency_check_grid
mpi_beam_distribute calls ebfb, bunch, loc_nbpart
fluid_den_mom_out calls exchange_pdata, endian
lp_window_xshift calls part_numbers, fields_left_xshift, cell_part_dist, particles_inject, fluid_left_xshift
tot_num_part calls loc_npart
part_pdata_out calls loc_npart, intvec_distribute, mpi_write_part, endian
prl_den_energy_interp calls loc_npart, loc_yg, spec, env, jc, loc_zg, den_zyxbd, mass
set_envelope calls lp_end, xf_loc, xc_loc, init_envelope_field, y0_cent, init_gprof_envelope_field, lpx, lp_delay, lp_in, loc_xgrid, z0_cent
vint_bcast calls mpi_bcast
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
init_lp_inc0_fields calls loc_ygrid, loc_yg, loc_zg, get_2dlaser_gprof_fields_lp, loc_zgrid, get_laser_gprof_fields_lp, loc_xg, get_plane_wave_lp, get_laser_fields_lp, get_2dlaser_fields_lp
multi_layer_twosp_target calls spec, wghpt, xpt, p_alloc, set_uniform_yz_distrib, loc_xpt, loc_wghx
fields_left_xshift calls exchange_bdx_data
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
preplasma_multisp calls spec, wghpt, xpt, p_alloc, set_uniform_yz_distrib, loc_xpt, loc_wghx
init_envelope_field calls loc_ygrid, loc_yg, loc_zg, loc_zgrid, loc_xg
env_amp_prepare calls env_grad
one_layer_nano_tubes calls loc_ypt, spec, loc_zpt, wghpt, loc_wghyz, xpt, init_random_seed, p_alloc, ypt, gasdev, loc_xpt, mpi_yz_part_distrib, zpt
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
init_gprof_envelope_field calls loc_ygrid, loc_yg, loc_zg, loc_zgrid, loc_xg
multi_layer_gas_target calls spec, wghpt, xpt, p_alloc, mpi_x_part_distrib, set_uniform_yz_distrib, loc_xpt, loc_wghx
envelope_struct_data calls allreduce_dpreal
mpi_write_part calls mpi_file_open, mpi_file_set_view, mpi_file_write, mpi_file_close
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd, lorentz_fact, nc_fluid_density_momenta
env_fields_average calls env_grad
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
multi_layer_threesp_target calls spec, wghpt, xpt, p_alloc, set_uniform_yz_distrib, loc_xpt, loc_wghx
init_cp_fields calls loc_ygrid, loc_yg, loc_zg, get_laser_fields_cp, loc_zgrid, get_plane_wave_cp, loc_xg
advance_lpf_fields calls fill_ebfield_yzxbdsdata, ef_bds, field_xadvect, rotb, rote, bf_bds
env_den_collect calls loc_yg, loc_zg, fill_curr_yzxbdsdata, den_zyxbd
cell_part_dist calls loc_npart, spec, ebfp, v_realloc
one_layer_nano_wires calls loc_ypt, spec, loc_zpt, wghpt, loc_wghyz, xpt, p_alloc, ypt, set_pgrid_ind, loc_xpt, mpi_yz_part_distrib, zpt, loc_wghx
env_amp_two_fields_prepare calls env_grad
particles_inject calls loc_npart, add_particles, v_realloc
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
fluid_left_xshift calls exchange_bdx_data
mpi_write_field calls mpi_file_open, mpi_file_set_view, mpi_file_write, mpi_file_close
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_maxw_solve, env_bds, env_lpf_solve
bunch_corr calls allreduce_dpreal
env_maxw_solve calls potential_lapl
from_ppc_to_npx_npy_npz calls isprime
mpi_x_part_distrib calls wghpt, xpt, loc_xpt, loc_wghx
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
field_xadvect calls trid_der1
add_particles calls init_random_seed, gasdev
env_bds calls loc_yg, loc_zg
fill_curr_yzxbdsdata calls exchange_bdx_data
rotb calls loc_yg, loc_zg
set_pgrid_ind calls ypt, zpt
env_lpf_solve calls pp_lapl
set_uniform_yz_distrib calls loc_ypt, loc_zpt, loc_wghyz, ypt, set_pgrid_ind, mpi_yz_part_distrib, zpt
rote calls loc_yg, loc_zg
mpi_yz_part_distrib calls loc_ypt, loc_zpt, loc_wghyz, ypt, zpt
bf_bds calls loc_yg, loc_zg, loc_xg
nc_fluid_density_momenta calls loc_yg, loc_zg
pp_lapl calls loc_yg, loc_zg